### PR TITLE
Modifications to get json schema to validate all json examples

### PR DESCRIPTION
**Pull request by tmorrell**
I'm working on adding 4.2 support to the python datacite package, and noticed there are a couple inconsistencies between the json examples and json schema.  This PR is one way of resolving these inconsistencies, but might not be the best.  Summary of changes:

In json examples:
- Change identifiers to identifier, remove extra identifiers, and have DOIs be the form 10.1234/111. This seems most consistent with the spec, but the flexibility of multiple identifiers is nice.  It might be better to modify the schema instead.
- Add contributorType to all Contributor objects
- Add resourceType to all records

In the json schema:
- Change date validation.  A year will match all the validation patterns, so the oneOf check won't work.

### CODE REVIEW

**Comment by mfenner** [comment]
Thanks @tmorrell, I will have a look. The JSON schema is still work in progress, so your help is highly appreciated. cc @mark-saeon

**Comment by tmorrell** [comment]
Thanks @mfenner! Another question on the current json examples - datacite-example-polygon-v4.json has polygonPoint values nested like:

"geoLocationPolygon": [
        {
          "polygonPoint": {
            "pointLongitude": "4.1738852605822",
            "pointLatitude": "52.03913926329928"
          }
        },
        {
          "polygonPoint": {
            "pointLongitude": "4.177180694215117",
            "pointLatitude": "52.04164225918711"
          }
        }

Couldn't this be simplified to:

"geoLocationPolygon": [
          "polygonPoint": {
            "pointLongitude": "4.1738852605822",
            "pointLatitude": "52.03913926329928"
          },
          "polygonPoint": {
            "pointLongitude": "4.177180694215117",
            "pointLatitude": "52.04164225918711"
          }

**Comment by tmorrell** [comment]
I've removed agency as a required property from the schema.  This isn't in the XML examples, looks to be something that DataCite uses internally, and is still available as an optional property.

**Comment by mfenner** [comment]
@tmorrell I would keep the identifiers property for now, as the JSON is heavily used internally in the Elasticsearch index and API. The rest looks good.

**Comment by tmorrell** [comment]
That was fast!  Thanks!

**Pull request merged**
